#ifndef __EvtFramePrincipal__
#define __EvtFramePrincipal__

/**
@file
Subclass of FramePrincipal, which is generated by wxFormBuilder.
*/

#include "FramePrincipal.h"

//// end generated include
#include "Directory.h"
/** Implementing FramePrincipal */
class EvtFramePrincipal : public FramePrincipal
{
	protected:
		// Handlers for FramePrincipal events.
		void OnButton_List_Contacts_Click( wxCommandEvent& event );
		void OnButton_Ajout_Contact_Click( wxCommandEvent& event );
		void OnButton_Delete_Contact_Click( wxCommandEvent& event );
		void OnButton_Search_Contact_Click( wxCommandEvent& event );
	public:
		/** Constructor */
		EvtFramePrincipal( wxWindow* parent );
	//// end generated class members
		~EvtFramePrincipal();
		Directory *repertoire = new Directory;





};

#endif // __EvtFramePrincipal__
