#ifndef __EvtFramePrincipal__
#define __EvtFramePrincipal__

/**
@file
Subclass of FramePrincipal, which is generated by wxFormBuilder.
*/

#include "FramePrincipal.h"

//// end generated include
#include <wx/log.h>

/** Implementing FramePrincipal */
class EvtFramePrincipal : public FramePrincipal
{
	protected:
		// Handlers for FramePrincipal events.
		void OnButton_Contacts_Click( wxCommandEvent& event );
		void OnButton_Add_Click( wxCommandEvent& event );
		void OnButton_Delete_Click( wxCommandEvent& event );
		void OnButton_Search_Click( wxCommandEvent& event );
	public:
		/** Constructor */
		EvtFramePrincipal( wxWindow* parent );
	//// end generated class members

};

#endif // __EvtFramePrincipal__
