.PHONY: clean All

All:
	@echo "----------Building project:[ contact_management - Debug ]----------"
	@cd "contact_management" && "$(MAKE)" -f  "contact_management.mk"
clean:
	@echo "----------Cleaning project:[ contact_management - Debug ]----------"
	@cd "contact_management" && "$(MAKE)" -f  "contact_management.mk" clean
